# Generated by Django 3.2.6 on 2021-08-30 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField(max_length=500)),
                ('difficulty', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermidiate'), ('E', 'Experience')], default='B', max_length=1)),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trail')),
            ],
        ),
    ]
