# Generated by Django 3.2.6 on 2021-08-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='hike',
            new_name='trail',
        ),
    ]
