# Generated by Django 3.2.6 on 2021-08-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210830_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='review',
        ),
    ]
